### ISSUE TITLE
DateTimeFormatter: access to calculated pattern

### ISSUE THREAD

**Issue by Strate** [andyearnshaw/Intl.js#160]
Hi all!
How about to expose access to calculated pattern?
In fact, at least google chrome browser do that in `resolve.pattern` options.

Or, alternativelly, could you move your implementation of `best-fit` to separate module to use it outside of polyfill?

**Comment by caridy** [comment]
@Strate about exposing the pattern, this is something we have been thinking about (more info here: https://github.com/tc39/ecma402/issues/21), but that discussion doesn't belong to the polyfill itself, but the 402 standard, the polyfill just implement what the standard spec is saying :)

As for the exposing best-fit, that's implementation dependent, I doubt that the expect will expose that in any way. I myself will oppose to that since most implementations are calling ICU directly except for chakra, which uses Windows APIs directly.
