### ISSUE TITLE
createRegExpRestore throws an error when RegExp.lastMatch is long

### ISSUE THREAD

**Issue by mtlewis** [andyearnshaw/Intl.js#196]
We're running into an issue with createRegExpRestore generating expressions that are over the size limit.  As createRegExpRestore is generating an expression based on RegExp.lastMatch, when the last matching string was extremely long, the expression generated was therefore too long and caused an error to be thrown.

We've been kicking this around here at work, and suspect that there may not be a perfect solution to the problem of needing to restore the RegExp static properties after interacting with regular expressions.  To that end, I'm proposing that we make this behavior optional - I'll be sending a PR for this.

**Comment by caridy** [comment]
@mtlewis thanks for looking at this. I'm not sure what @andyearnshaw thinks about it, but I will try to explain my mental model:

1. compliance with 402 is important, especially because we run 262 tests to validate that compliance, but I'm open to have a loosely mode in which this is not enforced.
2. A loosely mode could very well be the default mode, and the strict mode can be optional.
3. if an error occur (due to the restoration process), a warning doesn't cut it for me, an error should be issued.

PR #198 fails on the 3rd bullet point, and PR #197 seems like it aligns with the 1st bullet, but will require more work to make that the default behavior, and enable that strict mode when running 262 tests.

**Comment by nosilleg** [comment]
@caridy Your preferred solution should work for us, since we don't use any packages (that we know of) that require non mutating RegExp properties.

However, it does seem counter intuitive that enabling compliance can result in less compliant behaviour with code erroring that doesn't error in native implementations.  One could also argue that debugging issues caused by compliance turned off (#197) would be more difficult than with compliance turned on and a warning stating the issue (#198).

**Comment by andyearnshaw** [comment]
I agree with @caridy that we shouldn't swallow the error.  Try/catch is a well-known deopt, for one, but there's also the possibility of swallowing a legitimate error that makes it difficult for users to track down problems.

I think we could probably fix the restore function to use smaller regexes, by using `.exec()`, modifying `.lastIndex` and using `[\s\S]{,x}`, where x is the length of the match or sub-expression match.  This minimises the risk of us hitting the limit on characters.

I'm also totally fine with a "loose mode", as most people don't care about these properties being tainted anyway.

**Comment by mtlewis** [comment]
@andyearnshaw @caridy thanks very much for your feedback and suggestions guys!  @nosilleg and I worked on this together today, and came up with #201.  The PR still contains the parameterisation of the cache/restore functionality, but it also implements Andy's suggestion to use lastIndex and length-based regexes to shorten the generated expression.  Keen to hear your thoughts!

**Comment by mtlewis** [comment]
@andyearnshaw @caridy #201 is ready to go from our perspective - anything else we can do to help expedite the merge of this fix?

**Comment by caridy** [comment]
will do as soon as I get a chance this week.
