### ISSUE TITLE
Set default locale in node

### ISSUE THREAD

**Issue by osela** [andyearnshaw/Intl.js#206]
It seems the default locale is set to be the first locale that's added using __addLocaleData, and there is no public API to change it.

When using the library in node environment, I get all the locales by default and have no control on the order by which they are added, so I end up with 'af' as the default locale.

Is there a way to set the default locale that I missed?

**Comment by caridy** [comment]
@bumpy1 we have discussed this in the past, not in the context of the polyfill, but in the context of Intl in node in general, and we have no way around it, since each process will probably serve multiple requests, with different language and locale negotiation process, you will have to find a way to pass the locale to all Intl constructors, maybe using some sort of abstraction.

As for the polyfill, the way to do this is by doing something like this:

```
global.IntlPolyfill = require('intl/lib/core.js');
require('intl/locale-data/jsonp/en.js');  // default locale because it is the first one added
require('intl/locale-data/complete.js'); // add all others

// hack to export the polyfill as global Intl if needed
if (!global.Intl) {
    global.Intl = global.IntlPolyfill;
    global.IntlPolyfill.__applyLocaleSensitivePrototypes();
}
```

Instead of importing the main module in this package. I will be ok if you want to send a PR to make this the default behavior, or maybe changing the generation of complete.js to have `en` as the first one to be registered.

/cc @srl295

**Comment by bumpy1** [comment]
@caridy Thanks for your detailed response. 

Setting `en` as the first locale to be registered is probably a good idea anyway. I'll try to do it and send a PR.

As for the problems with default locale in node - I understand the problem, but I still believe there is value in the ability to set the default locale manually. First, Intl may be used in contexts that are not part of the request process (e.g background workers). Secondly, even in the context of a request I think I would like to use something like:

`
new Intl.NumberFormat(currentUser.locale).format(number);
`

and have Intl fallback to the default locale I chose if currentUser.locale isn't supported, instead of making a new abstraction.

What do you think?

**Comment by srl295** [comment]
@bumpy1 we should probably discuss elsewhere (perhaps http://github.com/nodejs/Intl/issues ) but setting the default locale as a concept has a number of problems.

 It's common to cache the default-locale contents, and such caches would be invalidated by changing the locale ID. From an `Intl` perspective, the default locale isn't required to be expressed by a string id accessible to the user. For example, an OS or other platform may have customizations (control panel etc) which are reflected in the default output but not expressed conveniently by an id.

From a JavaScript perspective, how do you know that your code is the only user of localization, and that there isn't other middleware involved? 

From an implementation perspective in a library such as [ICU](http://icu-project.org), setting the default locale in one thread could cause unexpected behavior in others.

Hope this helps. I'd enjoy hearing more detail on the use cases. In general, I think the default locale should be something chosen very early, and not switched around.
