### ISSUE TITLE
Armenian (locale "hy") is not working

### ISSUE THREAD

**Issue by bagratzakaryan** [andyearnshaw/Intl.js#323]
Hello, 
I would like to make Date in Armenian (locale "hy") but in my case when I include the CDN Javascript into HTML it is not working, and show "2018 M12 17, Mon". 

    <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Intl.~locale.hy"></script>
    <script>
        var x = new Intl.DateTimeFormat(
            'hy', {
                weekday: 'long',
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            }).format(new Date);

        console.log(x);
    </script>

How can I solve this issue ?

**Comment by okuryu** [comment]
The polyfill service applies the pollyfill to only an user agent which doesn't have the Intl feature implementation. This means the polyfill service doesn't apply the polyfill if you're using Chrome since Chrome supports the Intl features.

So, I've verified your result `2018 M12 17, Mon` on Chrome. It's a behavior of Chrome not Intl pollyfill. I also found an issue related to `hy` locale for Chromium ( [#842524](https://bugs.chromium.org/p/chromium/issues/detail?id=842524) ). It might be related to your problem.

As a workaround for your problem, please try following step. You may be able to resolve your issue.

1. install the Intl pollyfill via npm
```
$ npm install intl
```
2. create a `test.html` file like this
```html
<script src="./node_modules/intl/dist/Intl.js"></script>
<script src="./node_modules/intl/locale-data/jsonp/hy.js"></script>
<script>
var x = new IntlPolyfill.DateTimeFormat('hy', {
  weekday: 'long',
  year: 'numeric',
  month: 'long',
  day: 'numeric'
}).format(new Date);

console.log(x);
</script>
```
3. open the `test.html` and try to check the console on your browser

**Comment by bagratzakaryan** [comment]
Thank you very much!
